export const CONTEXT_HEADERSTATE = 'CONTEXT_HEADERSTATE';
export const CONTEXT_REGISTERITEM = 'CONTEXT_REGISTERITEM';
export const CONTEXT_SETDESCRIPTION = 'CONTEXT_SETDESCRIPTION';
export const CONTEXT_ITEMINDEX = 'CONTEXT_ITEMINDEX';

export const AUTOPLAY_INTERVAL_MS = 5000;
